name: Tag and Zip on Tag Push

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build-and-zip-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build || echo "Skipping build as it doesn't exist."

      - name: Zip Files for Tag
        run: |
          zip -r simple-project.zip . -x '*node_modules*' '*.git*' '*.md' '.github*'

      # - name: Create Release for Tag
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     release_name: ${{ github.ref_name }} Release
      #     draft: false
      #     prerelease: false
      #     release: false

      - name: Upload Zip to Tag
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./simple-project.zip
          asset_name: simple-project.zip
          asset_content_type: application/zip
