name: Tag and Zip on Push

on:
  push:
    tags:
      - '*' # Triggers on any tag push

jobs:
  build-and-zip-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to Node v20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build # Ensure you have a build script in package.json

      - name: Zip Files for Tag
        run: |
          zip -r simple-project-${{ github.ref_name }}.zip . -x '*node_modules*' '*.git*' '*.md' '.github*'

      # Commenting out release creation step so it only tags and zips
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     release_name: Release ${{ github.ref_name }}
      #     draft: false
      #     prerelease: true

      # Upload the zip file as a build artifact instead of release asset
      - name: Upload Zip as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: simple-project-${{ github.ref_name }}.zip
          path: ./simple-project-${{ github.ref_name }}.zip
